version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: psql-local
    environment:
      POSTGRES_DB: "api_db"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api -d api_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  db-data:
